management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        info: /actuator/info
        prometheus: /metrics

server:
  port: 80

grpc:
  server:
    port: 9000
    permit-keep-alive-without-calls: true
